In [1]:
import pandas as pd
import sklearn 
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import numpy as np
from sklearn import feature_selection
import seaborn as sns
import openpyxl

In [2]:
nome_base='noronha'
df = pd.read_csv("P:\\ciencia_de_dados\\Correlacao_de_fundos\\Bases\\"  + nome_base + ".csv",delimiter=';',decimal=',',parse_dates=True)
df = df.dropna().drop_duplicates().rename(columns={'Unnamed: 0':'data'})

In [3]:
df = df.melt(id_vars='data', value_vars=list(df.columns[1:]), value_name="FinancialPrice",var_name='Product')

In [4]:
#Calculo das colunas temporais
df['data']=pd.to_datetime(df['data'],format = '%d/%m/%Y')
df['MesAno'] = df['data'].dt.strftime('%m-%Y')
df['Mes_nomial']=df['data'].dt.strftime('%b')
df['Mes']=df['data'].dt.strftime('%m').astype(int)
df['Ano']=df['data'].dt.strftime('%Y').astype(int)
df

,data,Product,FinancialPrice,MesAno,Mes_nomial,Mes,Ano
0,2019-01-04,NORONHM BZ Equity,1.010293,01-2019,Jan,1,2019
1,2019-01-11,NORONHM BZ Equity,1.013655,01-2019,Jan,1,2019
2,2019-01-18,NORONHM BZ Equity,1.017839,01-2019,Jan,1,2019
3,2019-01-25,NORONHM BZ Equity,1.020638,01-2019,Jan,1,2019
4,2019-02-01,NORONHM BZ Equity,1.025252,02-2019,Feb,2,2019
...,...,...,...,...,...,...,...
715,2021-09-03,IBX Index,50174.570000,09-2021,Sep,9,2021
716,2021-09-10,IBX Index,49013.260000,09-2021,Sep,9,2021
717,2021-09-17,IBX Index,47623.990000,09-2021,Sep,9,2021
718,2021-09-24,IBX Index,48343.840000,09-2021,Sep,9,2021
719,2021-10-01,IBX Index,48123.070000,10-2021,Oct,10,2021

In [6]:
#Cria a coluna retorno e seta NaN na primeira linha de cada fundo
df.sort_values(by=["Product",'data'],ascending=False,inplace=True)
df['FinancialPrice']=pd.to_numeric(df["FinancialPrice"], downcast="float")
df["Retorno_1"] = (df.FinancialPrice.shift())/(df.FinancialPrice)
df.loc[df.drop_duplicates('Product').index.values,'Retorno_1'] = np.NaN
df['Retorno'] = df.Retorno_1.shift(periods=-1)
df['Retorno'] = (df["Retorno_1"]-1)*100
df

,data,Product,FinancialPrice,MesAno,Mes_nomial,Mes,Ano,Retorno_1,Retorno
143,2021-10-01,NORONHM BZ Equity,1.174563,10-2021,Oct,10,2021,NaN,NaN
142,2021-09-24,NORONHM BZ Equity,1.176622,09-2021,Sep,9,2021,0.998250,-0.174952
141,2021-09-17,NORONHM BZ Equity,1.173783,09-2021,Sep,9,2021,1.002418,0.241840
140,2021-09-10,NORONHM BZ Equity,1.169029,09-2021,Sep,9,2021,1.004066,0.406635
139,2021-09-03,NORONHM BZ Equity,1.166516,09-2021,Sep,9,2021,1.002154,0.215447
...,...,...,...,...,...,...,...,...,...
436,2019-02-01,BZRFIMAB Index,6516.036133,02-2019,Feb,2,2019,0.984294,-1.570553
435,2019-01-25,BZRFIMAB Index,6413.761230,01-2019,Jan,1,2019,1.015946,1.594615
434,2019-01-18,BZRFIMAB Index,6399.400879,01-2019,Jan,1,2019,1.002244,0.224400
433,2019-01-11,BZRFIMAB Index,6363.235840,01-2019,Jan,1,2019,1.005683,0.568342
432,2019-01-04,BZRFIMAB Index,6302.765137,01-2019,Jan,1,2019,1.009594,0.959432

In [11]:
df.to_csv('P:\\ciencia_de_dados\\Correlacao_de_fundos\\Desenvolvimento\\1DataPrep\\base_'+ nome_base + '.csv',sep =';',decimal=',')