In [1]:
import pandas as pd
import sklearn 
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import numpy as np
from sklearn import feature_selection
import seaborn as sns
import scipy.stats
from matplotlib import pyplot as plt
import math
import openpyxl
from  matplotlib.colors import LinearSegmentedColormap
import seaborn as sns
import xlsxwriter
from sklearn import feature_selection
import datetime

In [2]:
#Fundo a ser analisado
nome_da_base = 'bookx'#'book_pagaya_riverview'
col_fundos_input = ['JPEIGLSP Index','BRL Curncy','CAD Curncy','AUD Curncy']#['Pagaya Opportunity Fund','Riverview ALF']
nome_benchmark = 'DXY Index'#"IBOXHY Index"
diaria=0
tempo = 12 #252
const = 0.03
df=pd.read_csv('P:\\ciencia_de_dados\\Correlacao_de_fundos\\Desenvolvimento\\1DataPrep\\base_'+ nome_da_base + '.csv',sep =';',index_col=0,decimal=',')

if diaria==1:
    df_diaria = pd.read_csv('P:\\ciencia_de_dados\\Correlacao_de_fundos\\Desenvolvimento\\1DataPrep\\base_'+ nome_benchmark + '.csv',sep =';',index_col=0,decimal=',')
    df = pd.concat([df_diaria, df])

In [3]:
df['Retorno_Positivo'] = np.where(df.Retorno>=0, 1, 0)
df['Retorno_Negativo'] = np.where(df.Retorno<0, 1, 0)

In [4]:
df.head()

,index,Product,MesAno,data,FinancialPrice,Mes_nomial,Mes,Ano,Retorno_1,Retorno,Retorno_Positivo,Retorno_Negativo
677,677,JPEIGLSP Index,10-2021,2021-10-20,333.00,Oct,10,2021,NaN,NaN,0,0
665,665,JPEIGLSP Index,09-2021,2021-09-30,324.37,Sep,9,2021,1.026606,0.026605,1,0
653,653,JPEIGLSP Index,08-2021,2021-08-31,327.44,Aug,8,2021,0.990624,-0.009376,0,1
641,641,JPEIGLSP Index,07-2021,2021-07-30,331.83,Jul,7,2021,0.986770,-0.013230,0,1
629,629,JPEIGLSP Index,06-2021,2021-06-30,312.50,Jun,6,2021,1.061856,0.061856,1,0

In [5]:
df_sub = df.pivot(index=["data","Ano","Mes"], columns="Product", values="Retorno_1")
df_sub = df_sub.reset_index()
df_sub = df_sub.dropna()
#df_sub = df_sub.set_index("Ano")

In [6]:
df_sub.head()

Product,data,Ano,Mes,AUD Curncy,BRL Curncy,CAD Curncy,DXY Index,JPEIGLSP Index
0,2010-03-31,2010,3,1.016745,0.979220,0.991137,1.003178,1.050013
1,2010-04-30,2010,4,0.990375,1.057430,1.052373,1.058035,1.347012
2,2010-05-31,2010,5,0.946442,0.997983,0.992437,1.014261,0.982793
3,2010-06-30,2010,6,1.029778,0.953612,1.000941,0.973011,0.999532
4,2010-07-30,2010,7,1.017394,0.990070,0.997744,0.967937,0.896858

In [7]:
#Cria a df_sub1 para calculo do tracking error 
def f(x):
    print(x.name)
    return (x.div(df_sub[nome_benchmark]))#divisao entre o o retorno do fundo com o do benchmark

df_sub1 = df_sub.apply(lambda x: f(x) if x.name in col_fundos_input else x)

AUD Curncy
BRL Curncy
CAD Curncy
JPEIGLSP Index

In [8]:
df_sub1

Product,data,Ano,Mes,AUD Curncy,BRL Curncy,CAD Curncy,DXY Index,JPEIGLSP Index
0,2010-03-31,2010,3,1.013523,0.976118,0.987997,1.003178,1.046687
1,2010-04-30,2010,4,0.936051,0.999428,0.994648,1.058035,1.273125
2,2010-05-31,2010,5,0.933135,0.983951,0.978483,1.014261,0.968975
3,2010-06-30,2010,6,1.058342,0.980064,1.028705,0.973011,1.027257
4,2010-07-30,2010,7,1.051095,1.022866,1.030794,0.967937,0.926566
...,...,...,...,...,...,...,...,...
134,2021-05-31,2021,5,0.978697,0.937014,1.002605,1.010043,0.977112
135,2021-06-30,2021,6,0.963299,1.012887,1.014635,1.008111,1.053313
136,2021-07-30,2021,7,0.977146,1.022941,0.999720,1.006400,0.980495
137,2021-08-31,2021,8,0.999205,0.996966,0.991374,1.008229,0.982539
138,2021-09-30,2021,9,0.999990,1.024101,0.987063,1.001887,1.024672

In [9]:
df_concat = pd.concat([df_sub, df_sub1[col_fundos_input].add_suffix('_spread')], axis=1, join="inner")
col_fundos = df_concat.columns[3:]
df_concat.head()

Product,data,Ano,Mes,AUD Curncy,BRL Curncy,CAD Curncy,DXY Index,JPEIGLSP Index,JPEIGLSP Index_spread,BRL Curncy_spread,CAD Curncy_spread,AUD Curncy_spread
0,2010-03-31,2010,3,1.016745,0.979220,0.991137,1.003178,1.050013,1.046687,0.976118,0.987997,1.013523
1,2010-04-30,2010,4,0.990375,1.057430,1.052373,1.058035,1.347012,1.273125,0.999428,0.994648,0.936051
2,2010-05-31,2010,5,0.946442,0.997983,0.992437,1.014261,0.982793,0.968975,0.983951,0.978483,0.933135
3,2010-06-30,2010,6,1.029778,0.953612,1.000941,0.973011,0.999532,1.027257,0.980064,1.028705,1.058342
4,2010-07-30,2010,7,1.017394,0.990070,0.997744,0.967937,0.896858,0.926566,1.022866,1.030794,1.051095

In [10]:
#Retorno Mensal
def function_retorno(df,i,const,col_fundos):

    pivot_table = pd.pivot_table(df,index=['Ano'],values=[col_fundos[i]],fill_value=1,aggfunc='prod',columns=['Mes'])#,margins=True,margins_name="Year")
    pivot_table=pivot_table.rename(columns={1: 'Jan', 2:"Feb",3:"Mar", 4:"Apr", 5:"May", 6:"Jun",7:"Jul", 8:"Aug", 9:"Sep", 10:"Oct", 11:"Nov", 12:"Dec"})
    
    ITD_Matrix = [df[df.Ano <= i_ano][col_fundos[i]].prod() for i_ano in df.Ano.unique()]
    YTD_Matrix = [df[df.Ano == i_ano][col_fundos[i]].prod() for i_ano in df.Ano.unique()]
    
    ITD_df=pd.DataFrame(ITD_Matrix, columns = [col_fundos[i]] ,index=df_concat.Ano.unique())
    YTD_df=pd.DataFrame(YTD_Matrix, columns = [col_fundos[i]] ,index=df_concat.Ano.unique())
    
    ITD_df.columns = pd.MultiIndex.from_product([ITD_df.columns, ['Retorno ITD']])
    YTD_df.columns = pd.MultiIndex.from_product([YTD_df.columns, ['Retorno YTD']])
    
   
    
    pivot_table = pd.concat([pivot_table,YTD_df,ITD_df],axis=1)
    pivot_table = pivot_table-1
    
    
    
    # backgroung color mapping
    my_cmap=LinearSegmentedColormap.from_list('rg',["r", "w", "g"], N=256)
    pivot_table.index.name="Retorno Mensal"
    #pivot_table = pivot_table.style.background_gradient(cmap=my_cmap,vmin = -const,vmax = const)
    
    return pivot_table.applymap('{:.1%}'.format)

In [11]:
function_retorno(df_concat,0,const,col_fundos)

Product        AUD Curncy                                                   \
Mes                   Jan    Feb    Mar    Apr    May    Jun    Jul    Aug
Retorno Mensal
2010                 0.0%   0.0%   1.7%  -1.0%  -5.4%   3.0%   1.7%   5.6%
2011                -0.5%   1.5%   5.8%   0.4%  -2.3%   2.8%  -0.2%  -2.5%
2012                 1.4%   0.0%  -3.1%  -0.4%  -2.3%   3.0%   0.7%  -0.3%
2013                -1.5%   0.5%   0.6%  -1.7%  -5.8%  -4.9%  -1.0%   3.4%
2014                -0.2%   2.4%   1.8%  -0.5%   0.5%   0.7%  -1.5%   0.2%
2015                -4.1%  -0.1%   1.8%   1.1%  -3.9%  -1.2%  -3.7%  -3.0%
2016                -0.9%   6.0%   1.9%  -1.9%  -0.7%   0.2%   0.9%  -0.1%
2017                 1.7%   0.2%  -1.3%  -1.2%   2.0%   4.2%  -0.0%   0.7%
2018                -0.7%  -2.2%  -1.2%  -2.6%   1.1%  -2.6%  -0.5%  -1.9%
2019                 0.3%  -1.9%   0.6%  -1.8%  -0.6%   0.9%  -3.3%   0.5%
2020                -3.9%  -1.6%  -1.2%   1.5%   5.5%   2.5%   2.4%   0.1%
2021                 2.1%  -1.9%  -0.3%   0.6%  -1.1%  -2.9%  -1.7%   0.7%

Product
Mes               Sep    Oct    Nov    Dec Retorno YTD Retorno ITD
Retorno Mensal
2010             2.5%   2.2%   0.2%   0.5%       11.3%       11.3%
2011             0.1%  -1.9%  -2.2%   3.5%        4.2%       15.9%
2012            -1.6%   0.9%   0.9%   0.3%       -0.6%       15.2%
2013             2.0%  -1.9%  -3.9%  -1.1%      -14.6%       -1.6%
2014            -5.6%  -0.7%  -3.3%  -3.3%       -9.2%      -10.6%
2015             2.3%  -1.4%   1.2%  -0.5%      -11.2%      -20.6%
2016             0.4%   0.5%  -3.4%   1.1%        3.8%      -17.5%
2017            -2.1%  -2.2%   1.1%   4.1%        6.9%      -11.8%
2018            -0.9%   1.5%   0.4%  -1.5%      -10.6%      -21.2%
2019             0.3%   0.0%   1.3%   0.4%       -3.1%      -23.7%
2020            -1.8%   2.0%   4.0%   1.5%       11.1%      -15.2%
2021             0.2%   0.0%   0.0%   0.0%       -4.2%      -18.7%

In [12]:
a_number = 0.20
percentage = "{:.2%}".format(a_number)
print(percentage)

20.00%

In [20]:
def float_formatter(a_number):
    return "{:.1%}".format(a_number)

def vol_anualizada(x,tempo):
    z = x.std() * (tempo**(1/2))
    return z

def retorno_anualizado(x,tempo):
    return (x.product()**(tempo/float(x.count())) - 1)

def MDD(x):
    return min(((x/x.cummax()) - 1))

def retorno_total(x):
    return (x.prod() - 1)

def Meses_Positivos(x): #Gambiarra para nomear sum
    return x.sum()

def Meses_Negativos(x):
    return x.sum()

def Periodo(x):
    return datetime.datetime.strptime(min(x), '%Y-%m-%d').strftime('%b-%Y')+' a ' + datetime.datetime.strptime(max(x), '%Y-%m-%d').strftime('%b-%Y')


df.sort_values(by=["Product",'data'],ascending=False,inplace=True)


table = df.groupby('Product').agg({"Retorno": ['max','min','mean',lambda (x: vol_anualizada(x,12)] ,"Retorno_Negativo":Meses_Negativos,"Retorno_Positivo": Meses_Positivos,"Retorno_1" : [retorno_total, lambda x: retorno_anualizado(x,tempo)]}).rename(columns={'<lambda_0>':'Volatilidade Anualizada','<lambda_1>' :'Retorno Anualizado','retorno_total':'Retorno Total'})
table.columns = table.columns.droplevel(0)
table["Sharpe"] = (table["Retorno Anualizado"] / table["Volatilidade Anualizada"])



df.sort_values(by=["Product",'data'],ascending=True,inplace=True)
table2 = df.groupby('Product').agg({"FinancialPrice":MDD}).rename(columns={"FinancialPrice":"Maximo Drawdown"})

x=pd.concat([table,table2],axis=1)
print(x)
for col_name in ['max','min','mean','Volatilidade Anualizada','Retorno Total','Retorno Anualizado','Maximo Drawdown']:
    x[col_name] = x[col_name].apply(lambda x: float_formatter(x))

#pd.options.display.float_format = '{:.1}'.format
df_univar = x.T

df_univar.rename(index = {'Retorno Total':"Retorno Acumulado ITD","Meses_Positivos": "Meses Positivos", "Meses_Negativos":"Meses Negativos","max":"Retorno Mensal Máximo","min" : "Retorno Mensal Minimo", "mean": "Média dos Retornos Mensais"}, inplace=True)
df_univar.index.name=Periodo(df.data)

df_univar

SyntaxError: invalid syntax (<ipython-input-20-f4a54e72260a>, line 30)

In [ ]:
def regressao_linear(df,nome_do_fundo,nome_benchmark):   
    df_fundo = df.loc[df.Product == nome_do_fundo,['data','Retorno']]
    df_bench = df.loc[df.Product == nome_benchmark,['data','Retorno']]

    df_fundo.index = df_fundo['data']
    df_bench.index = df_bench['data']
    df_join =pd.merge(df_bench, df_fundo,how='inner',left_index=True, right_index=True).dropna()[['Retorno_x','Retorno_y']]

    #Regressao Linear total
    x = (df_join['Retorno_x']).values.reshape((-1, 1))
    y= (df_join['Retorno_y']).values.reshape((-1, 1))
    
    regr = sklearn.linear_model.LinearRegression()
    regr.fit(x, y)
    return regr.coef_[0][0],regr.intercept_[0]

k=0
v = []
for i in col_fundos_input:
    v.append(regressao_linear(df,i,nome_benchmark))
    
df_bivar = pd.DataFrame(v,index=col_fundos_input).rename(columns = {0:'Beta',1:'Alpha'}).T
df_bivar

#Tracking Error
v=[]
for i in col_fundos_input:
    v.append(np.std(df_sub1[i]))


df_bivar.loc['Tracking Error'] = [float_formatter(x) for x in v]
df_bivar.index.name = ' '
df_bivar

In [ ]:
df_sub.head()

In [ ]:
sklearn.feature_selection.mutual_info_regression(df_sub[col_fundos_input],df_sub[nome_benchmark])

In [ ]:
df_sub.iloc[:,3:] = (df_sub.iloc[:,3:] *100)-100

In [ ]:
sns.pairplot(data=df_sub.iloc[:,3:],kind="reg",plot_kws={'line_kws':{'color':'red','lw':1},'scatter_kws': {'s': 3}},corner= True)
plt.savefig('fig_pairplot.png')

In [ ]:
sns.kdeplot(data=df.reset_index(),x = 'Retorno',hue = 'Product',fill=True)
plt.savefig('retorno_density_distribution.png')

In [ ]:
df

In [ ]:
col_fundos1 =col_fundos_input
col_fundos1.append(nome_benchmark)

corr = df_sub[col_fundos_input].corr()

col_fundos1 =col_fundos_input
ax = sns.heatmap(
    corr,
    annot=True, 
    vmin=-1, vmax=1, center=0,
    cmap=sns.diverging_palette(20, 220, n=200),
    square=True
)
ax.set_xticklabels(
    ax.get_xticklabels(),
    rotation=45,
    horizontalalignment='right'
);
plt.savefig('CorrelationMatrix.png',dpi=200)

In [ ]:
#Descritivas anuais
df_anuais = df.groupby(['Ano','Product']).agg({"Retorno": ['count','max','min','mean',vol_anualizada] ,"Retorno_1" : ['prod',lambda x: retorno_anualizado(x,tempo)]}).unstack().T.reset_index().iloc[: , 1:]

In [ ]:
df_sub.sort_values(by=['data'],ascending=True,inplace=True)
df_sub

In [ ]:
#Teste do k
k=0
#Dia atual
print(df_sub['data'].iloc[k+60:k+60+1])
print(df_sub[x1][k:60+k])
print(df_sub[x1][(k+60-janela): (k+60)])

In [ ]:
coef_12=[]
coef_36=[]
coef_60=[]
coef_b=[]
data=[]


def func_corr_bootstrap(df,k,ativo1,ativo2):
    n1=30
    df_rand = df[k:(60+k)].sample(n = n1)
    return scipy.stats.pearsonr(df_rand[ativo1], df_rand[ativo2])[0]

def grafico_corr(df,ativo1,ativo2):
    for k in range(0,len(df[ativo1])-(60)):
    
        janela=12
        #Correlacao Simples lag de 12  Meses passados
        coef_12.append(scipy.stats.pearsonr(df[ativo1][(k+60-janela): (k+60)], df[ativo2][(k+60-janela): (k+60)])[0])

        janela=36
        #Correlacao Simples lag de 24  Meses passados
        coef_36.append(scipy.stats.pearsonr(df[ativo1][(k+60-janela): (k+60)], df[ativo2][(k+60-janela): (k+60)])[0])

        janela=60
        #Correlacao Simples lag de 60  Meses passados
        coef_60.append(scipy.stats.pearsonr(df[ativo1][(k+60-janela): (k+60)], df[ativo2][(k+60-janela): (k+60)])[0])
          
        #Correlacao Bootstrap lag de 5 anos passados
        coef_b.append(np.mean([func_corr_bootstrap(df,k,ativo1,ativo2) for i in range(1000)]))
        data.append(df['data'].iloc[k+60:k+60+1].values[0]) # Dia Atual comeca em index=60

    df_teste = pd.DataFrame(
        {'mes':data,
         'Correlacao_BoostStrapping': coef_b,
         'Correlacao_simples_12_meses': coef_12,  
         'Correlacao_simples_36_meses': coef_36,
         'Correlacao_simples_60_meses': coef_60
        })
    return df_teste

In [ ]:
coef_12=[]
coef_36=[]
coef_60=[]
coef_b=[]
data=[]


def func_corr_bootstrap(df,k,ativo1,ativo2):
    n1=30
    df_rand = df[k:(60+k)].sample(n = n1)
    return scipy.stats.pearsonr(df_rand[ativo1], df_rand[ativo2])[0]

def grafico_corr(df,ativo1,ativo2):
    for k in range(0,len(df[ativo1])-(60)):
    
        janela=12
        #Correlacao Simples lag de 12  Meses passados
        coef_12.append(scipy.stats.pearsonr(df[ativo1][(k+60-janela): (k+60)], df[ativo2][(k+60-janela): (k+60)])[0])

        janela=36
        #Correlacao Simples lag de 24  Meses passados
        coef_36.append(scipy.stats.pearsonr(df[ativo1][(k+60-janela): (k+60)], df[ativo2][(k+60-janela): (k+60)])[0])

        janela=60
        #Correlacao Simples lag de 60  Meses passados
        coef_60.append(scipy.stats.pearsonr(df[ativo1][(k+60-janela): (k+60)], df[ativo2][(k+60-janela): (k+60)])[0])
          
        #Correlacao Bootstrap lag de 5 anos passados
        coef_b.append(np.mean([func_corr_bootstrap(df,k,ativo1,ativo2) for i in range(1000)]))
        data.append(df['data'].iloc[k+60:k+60+1].values[0]) # Dia Atual comeca em index=60

    df_teste = pd.DataFrame(
        {'mes':data,
         'Correlacao_BoostStrapping': coef_b,
         'Correlacao_simples_12_meses': coef_12,  
         'Correlacao_simples_36_meses': coef_36,
         'Correlacao_simples_60_meses': coef_60
        })
    return df_teste

In [ ]:
x1 = 'DXY Index'
x2 = 'AUD Curncy'

In [ ]:
df_teste = grafico_corr(df_sub,x1, x2)

In [ ]:
# gca stands for 'get current axis'
ax = plt.gca()

df_teste.plot(kind='line',x='mes',y='Correlacao_BoostStrapping', color='black',linewidth=4 , ax=ax)
df_teste.plot(kind='line',x='mes',y='Correlacao_simples_12_meses', color='red', ax=ax)
df_teste.plot(kind='line',x='mes',y='Correlacao_simples_36_meses', color='blue', ax=ax)
df_teste.plot(kind='line',x='mes',y='Correlacao_simples_60_meses', color='green', ax=ax)

plt.xticks(rotation=90)
plt.tight_layout()
plt.grid() 
plt.ylim([-1, 1])
plt.show()


plt.savefig('corr.png',dpi=300)

In [ ]:
# Create a Pandas Excel writer using XlsxWriter as the engine.
writer = pd.ExcelWriter('book'+nome_da_base+'.xlsx', engine='xlsxwriter')
workbook = writer.book
worksheet = workbook.add_worksheet('Relatorio')
df_sub.to_excel(writer,sheet_name = 'UnstackRetornosPercentuais')
df.to_excel(writer, sheet_name='StackRetornos1')

options = {
    'width': 256,
    'height': 100,
    'x_offset': 10,
    'y_offset': 10,

    'font': {'color': 'white',
             'size': 20},
    'align': {'vertical': 'middle',
              'horizontal': 'center'
              },
    'gradient': {'colors': ['#3E9EBC',
                            '#2F778D',
                            ]},
}

options2 = {
    'width': 200,
    'height': 20,
    'x_offset': 10,
    'y_offset': 10,

    'font': {'color': 'white',
             'size': 10},
    'align': {'vertical': 'middle',
              'horizontal': 'center'
              },
    'gradient': {'colors': ['#800000',
                            '#800000',
                            ]},
}
options3 = {
    'width': 200,
    'height': 20,
    'x_offset': 10,
    'y_offset': 10,

    'font': {'color': 'white',
             'size': 10},
    'align': {'vertical': 'middle',
              'horizontal': 'center'
              },
    'gradient': {'colors': ['#3E9EBC',
                            '#2F778D',
                            ]},
}
worksheet.insert_textbox('B2', 'Relatório Estatístico',options)


writer.sheets['Relatorio'] = worksheet
spread_names = [s for s in df_concat.columns[3:] if 'spread' in s]

#Tabela de retornos coloridos
worksheet.insert_textbox('B8', 'Retorno do fundo - Retorno do benchmarck',options2)
table_size = len(df.Ano.unique()) + 4

for i in range(len(col_fundos)):
    function_retorno(df_concat,i,const,col_fundos).to_excel(writer,sheet_name = 'Relatorio',startrow=(8 + table_size*i), startcol=0,index_label='Retorno')
    if col_fundos[i] in spread_names:
        worksheet.insert_textbox('B'+ str((8 + table_size*i)), 'Spread do Retorno',options2)
    else:    
        worksheet.insert_textbox('B'+ str((8 + table_size*i)), 'Retorno',options3)
    
#Graficos
i = 2*table_size+table_size*i
worksheet.insert_image('A'+ str(i),'fig_pairplot.png')
worksheet.insert_image('O'+ str(i),'retorno_density_distribution.png')
worksheet.insert_image('O'+ str(i+20) ,'CorrelationMatrix.png')#,{'x_scale': 2, 'y_scale': 2})    

#Tabelas com os resultados
df_univar.to_excel(writer, sheet_name='Relatorio',float_format="%.2f",startrow=8,startcol = 17)
df_bivar.to_excel(writer, sheet_name='Relatorio',float_format="%.2f",startcol=17,startrow = (8+ len(df_univar)+2))
df_anuais.to_excel(writer, sheet_name='Anuais',float_format="%.2f")  
 
#Formata tamanho da coluna
writer.sheets['Relatorio'].set_column(17, 30, 25)
writer.sheets['Relatorio'].set_column(0, 0, 15)
writer.sheets['Relatorio'].set_column(13, 14, 15)

writer.save()

In [ ]:
#Descritivas mensais

#df[['Retorno','MesAno','Product']].groupby(['MesAno','Product']).describe().unstack()